#! /bin/sh

# Abort if any command returns an error value
set -e

# This script is called as the first step in removing the package from
# the system.  This includes cases where the user explicitly asked for
# the package to be removed, upgrade, automatic removal due to conflicts,
# and deconfiguration due to temporary removal of a depended-on package.

package_name=pve-manager-electrified;

case "$1" in
  remove|deconfigure|failed-upgrade)
    # simply stop all units (that are not critical). We might be here, because the user want to go pack to pve-manager by Proxmox. We can't guarantee, that the reload mechanism will work across this jump, so it's safer to just stop the service)
    UNITS="pvedaemon.service pveproxy.service pvenodejsserver.service spiceproxy.service pvestatd.service pvebanner.service pvescheduler.service pve-daily-update.timer"
    for unit in ${UNITS}; do
      echo "Stopping service $unit"
      systemctl stop "$unit"
    done
    ;;
  upgrade)
    if [ -L /usr/doc/$package_name ]; then
	rm -f /usr/doc/$package_name
    fi
    ;;
  *) echo "$0: didn't understand being called with \`$1'" 1>&2
     exit 0;;
esac

exit 0
